### ISSUE TITLE
Pressing Enter removes line with electric-indent-mode

### ISSUE THREAD

**Issue by AGoyet** [taquangtrung/lark-mode#1]
When pressing enter (RET), everything at the left of the cursor is removed (and the cursor moves to the beginning of the next line). This happens even in a new .lark file with a single rule `a: "a"`.

This only occurs if electric-indent-mode is enabled.

**Comment by taquangtrung** [comment]
I couldn't reproduce the issue. I also use `electric-indent-mode`. 

Can you test with a minimal Emacs environment on your side to make sure if the problem still occurs?

**Comment by xymaxim** [comment]
I can confirm this problem on GNU Emacs 29.1 (running via `emacs -Q`) with only lark-mode 20230327.1003 (installed from MELPA) loaded.

See the GIF below showing the reproduced issue.

![Peek 2023-12-21 03-10](https://github.com/taquangtrung/lark-mode/assets/1060604/cdcc91a1-d1bb-4283-a9f5-274d5d6ec426)

**Comment by taquangtrung** [comment]
@xymaxim: Thanks for the investigation! I just tested a fresh Emacs initialization and indeed there is that issue.
